const ACTION_TYPES = {
    LOGIN_CURRENT_USER: "LOGIN_CURRENT_USER",
    LOGOUT_CURRENT_USER: "LOGOUT_CURRENT_USER",
    SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
    SET_SUCCESS_MESSAGE: "SET_SUCCESS_MESSAGE",
    REGISTER_CURRENT_USER: "REGISTER_CURRENT_USER"
};
export default ACTION_TYPES;
